
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: debian-8.6
  - name: centos-6.8
  - name: centos-7.2

suites:
- name: default
  run_list:
    - recipe[virtualbox]
  attributes:
