
driver:
  name: vagrant

verifier:
  name: inspec

## needed for windows - not used for cookbook v2.1 era
#transport:
#  username: vagrant
#  password: vagrant
#  elevated: true
#  name: winrm

provisioner:
  name: chef_zero

platforms:
#  - name: ubuntu-16.04
  - name: ubuntu-18.04
#  - name: debian-9
## Stopping testing of CentOS as of v2.1 era (for now)
#  - name: centos-7
##
#  Never tested Mac
#  Will likley remove any hints of support.
## Stopped testing of Windows as of cookbook v2.1 era
#  - name: windows-2016
#    driver:
#      box: mwrock/Windows2016
#      gui: false
#    transport:
#      name: winrm

suites:
- name: default
  run_list:
    - recipe[virtualbox]
  attributes:
