
driver:
  name: vagrant

verifier:
  name: inspec

## needed for windows - not used for cookbook v2.1 era
#transport:
#  username: vagrant
#  password: vagrant
#  elevated: true
#  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9
  - name: centos-7
## Not worrying about Windows as of cookbook v2.1 era
#  - name: windows-2016
#    driver:
#      box: mwrock/Windows2016
#      gui: false
#    transport:
#      name: winrm

suites:
- name: default
  run_list:
    - recipe[virtualbox]
  attributes:
